language: python
dist: bionic
python:
- '3.6'
before_install:
- sudo rm -f /etc/boto.cfg
install:
- pip install -q .
- pip install coveralls
os:
- linux
script: coverage run --source=pythaisa setup.py test
after_success: coveralls
deploy:
  provider: pypi
  distributions: bdist_wheel
  user: wannaphong
  on:
    tags: true
  password:
    secure: ezXr5N0oHUukVRBQ0iidhw+CXxpHxTO008+XfcGyobTa6rEFuiT8CgLna4FJGB2ZU/ZQfpZGfPnHxEVJtoetBbVNCViVR76aZeD1y7FzS/a6uI0l5EOAwbKaj7fbkFaUev9eFS/GjQRNqn9u6XXHWen5LGkJUmjLue7udyPkPG/xtdXvMU0Tee2CqgGOOHbzHrxnFEqlZTRtRAAVqFOxa0lWBqryChgljWW0zeEjKHTM8NJ58qBHo/HU7ptJnLXEW/JYdWzcUSKtrqS8Mvqyb2SgetY5XCt4ENASATawoySF1woNmVf281iy1DiFd8qpcFAWAprDbfEOfvxXyzl3izkT8O3jmKeJmRSeaVG8jxPRD16uumaoB4CkRgqwQ2cyJZbFmzUAa2KQXZ6bgmMDmmnQIVGxAPNdYzZTMTz6NvmD8JppwXn7LNUZhWSEoOmbs+UgLk+wlQ0ZUHeptSNENAXdsTmBw58SCTjN8AFyxYFyR+5+5BB11RmRJz4RbJ29ivQOkVUQSzuHNxGWay0ekGLcJ846hke5ZpF0JuhWNS5x469M1/D+o4ZlTDlQFsR4Ym0RsFEldIIM7o/8aI0mbcFHknpJRAiR/fmdsQcQq0WdynwqtmwXdlZGzYnuBf/slgZxCJDRF6LeZQOrHgmz53G2zcmRpJ37suOQQcPAdUk=
